### ISSUE TITLE
replace /etc/cron.d/cleanup_scm_cache by systemd.timer

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#11909]
## Why?

Even on servers where obsservice.service is not started, this cronjob generates useless logging output/error messages.

## TODO
- [ ] Create systemd timer
- [ ] Create systemd service
  - [ ] Consider `ConditionPathExists=`
- [ ] define dependency to obsservice.service
- [ ] check if
