### ISSUE TITLE
Meta data gets not adapted after deleting user

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#9285]
A deleted user is still visible in webui and meta data after deleting him. 

A real life example is "mrdocs", still listed eg in "graphics" project, but not via /person/mrdocs anymore.

In other cases this might be a DSGVO problem (IMHO also a regression, but not 100%)

**Comment by hennevogel** [comment]
This is a more a feature (as in missing functionality) than a bug. Let me see what we do already and what we can do.

**Comment by hennevogel** [comment]
- [ ] remove all `Relationship`
- [ ] remove all attrib_namespace_modifiable_bies
- [ ] remove all attrib_type_modifiable_bies
- [ ] remove all comments
- [ ] remove all commit_activities
- [ ] remove all group_maintainers
- [ ] remove all groups_users
- [ ] remove all history_elements
- [ ] remove all messages
- [ ] remove all reviews
- [ ] remove all status_messages
- [X] delete the home project
- [X] blank `User.mail`
- [X] blanke `User.realname`

**Comment by adrianschroeter** [comment]
On Mittwoch, 25. März 2020, 17:24:01 CET wrote Henne Vogelsang:
> - [ ] remove all `Relationship`
> - [ ] remove all attrib_namespace_modifiable_bies
> - [ ] remove all attrib_type_modifiable_bies

not needed.

> - [ ] remove all comments

that would be good, yes

> - [ ] remove all commit_activities
> - [ ] remove all group_maintainers
> - [ ] remove all groups_users

this is no needed

> - [ ] remove all history_elements

that must not happen.

> - [ ] remove all messages

unsure if needed

> - [ ] remove all reviews

must not happen.

> - [ ] remove all status_messages
> - [X] delete the home project
> - [X] blank `User.mail`
> - [X] blanke `User.realname`
> 
> 
> 
> 


-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by hennevogel** [comment]
Maybe you can explain **why** something is not needed in your opinion? Because for instance `Relationship` is the use case you are asking for. `Relationship` is the connection between `User` and `Package` or `Project`.

**Comment by dmarcoux** [comment]
Any progress on this because it's affecting some requests like:
- https://build.opensuse.org/request/show/145699
- https://build.opensuse.org/request/show/40614
- https://build.opensuse.org/request/show/53809
- https://build.opensuse.org/request/show/898198
- and more...
